### ISSUE TITLE
Solve the problem with deprecated facker.unique method

### ISSUE THREAD

**Issue by dPaskhin** [dPaskhin/chat#17]
Details can be found [here](https://github.com/faker-js/faker/issues/1785)

TLDR.
1. **facker.unique** is going to be removed from [faker](https://github.com/faker-js/faker) in soon updates
2. There is an alternative approach to get this functionality as **facker.unique**, it can be found in the link above

**Comment by dPaskhin** [comment]
In the meantime, a UUID will be used as a temporary solution.

**Comment by MansurAliKoroglu** [comment]
I created a package to be used as a replacement to unique.

https://github.com/MansurAliKoroglu/enforce-unique

https://www.npmjs.com/package/enforce-unique

**Comment by dPaskhin** [comment]
@MansurAliKoroglu It's pretty good, thank you so much! I'll definitely use it
